quarkus:
  application:
    name: Library

  http:
    port: 8080

  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5435/library
    username: user
    password: pass

  devservices:
    enabled: false

  liquibase:
    migrate-at-start: true
    change-log: classpath:/db/changelog/db.changelog-master.yml